const data = {
  personal: {
    name: 'Ankit Kumar',
    occupation:
      "I'm an Aspiring Full Stack Developer, currently working as a System Engineer at Oracle Cerner",
    email: 'ankit2k825@gmail.com',
    number: '+91 6360041946',
    about:
      'Forward-thinking Full Stack Engineer with background as a Computer Science Graduate and System Engineer with 2 years experience. Accomplished projects troubleshooting and resolving issues by debugging programs and managing tasks. Increase proficiencies and offering expertise in cross platform application development',
    about2:
      'Expanding my limit to enhance and explore my knowledge in the business world. Understanding business goals and combining logic with aesthetics to create beautiful, consistent and functional design solutions',
    website: 'https://ankit-webdev.vercel.app/',
    image: 'image/profilePic.jpg',
    resumedownload:
      'https://drive.google.com/file/d/1g4Ui8Tkg7AOfBnFfKZzz4MJN4NLDXgd7/view?usp=drive_link',
    social: [
      {
        name: 'facebook',
        url: '',
        cName: 'fas fa-facebook',
      },
      {
        name: 'linkedin',
        url: '',
        cName: 'fas fa-linkedin',
      },
      {
        name: 'instagram',
        url: '',
        cName: 'fas fa-instagram',
      },
      {
        name: 'github',
        url: '',
        cName: 'fas fa-github',
      },
    ],
  },
  why: [
    {
      title: 'In-Depth Industry Experience',
      desc: '',
    },
    {
      title: 'Organized Design Process',
      desc: '',
    },
    {
      title: 'Expert in Key Skills',
      desc: '',
    },
    {
      title: 'Always Meet Deadlines',
      desc: '',
    },
  ],
  service: [
    {
      title: 'Design and Development',
      desc: 'Starting from single page landing sites to e-commerce sites, I help you visualize what you think, in the form of full-fledged websites',
    },
    {
      title: 'Responsive Design',
      desc: 'Fully responsive design compatible to most of the devices',
    },
    {
      title: 'UX Research',
      desc: "To give your project a kick-start. I'll provide you detailed UX research as of my 3+ years of UX experience",
    },
    {
      title: 'Cross Platform Applications',
      desc: 'Build for Android, IOS, Desktop and Web whatever is your need',
    },
    {
      title: 'SEO Strategies',
      desc: "A good copy does what thousands of better designs can't. That, along with other strategies like SEO, AdSense, Analytics etc. can take you far - in the long run.",
    },
  ],
  skills: {
    desc: 'Over 2 years of experience working with these skills and providing a best solution to the client',
    images: [
      'image/html.svg',
      'image/css.svg',
      'image/js.svg',
      'image/mongo.svg',
      'image/express.svg',
      'image/react.svg',
      'image/node.svg',
      'image/redux.svg',
      'image/bootstrap.svg',
      'image/tailwind.svg',
      'image/material.png',
      'image/firebase.png',
      'image/next.svg',
      'image/electron.svg',
      'image/graphql.svg',
      'image/mysql.svg',
      'image/postgresql.svg',
      'image/typescript.svg',
    ],
  },
  projects: [
    {
      title: 'Nian Devs',
      keySkills: [
        'NextJS',
        'TailwindCSS',
        'TypeScript',
        'MongoDB',
        'Cloudinary',
        'Serverless APIs',
        'Google Auth',
      ],
      image: 'project/nianDevs.png',
      desc: 'A web application, used to manage the profiles of developers and to connect them with hiring teams looking for freelancers, part-time, and full-time. Developers can use the too! to manage their own profiles. Powered with PWA and mode switching',
      url: 'https://nian-devs.vercel.app/',
    },
    {
      title: 'IPU Manager',
      keySkills: [
        'NextJS',
        'TailwindCSS',
        'MongoDB',
        'Cloudinary',
        'Serverless APIs',
        'JWT Auth',
      ],
      image: 'project/ipuManager.png',
      desc: 'A Credentials provider service built for a university to manage and assign emails and wifi services access, that can be control by university authorities, move online, to reduce the paperwork to ease the work of student and staff to operate from anywhere.',
      url: 'https://ipu-manager.vercel.app/',
    },
    {
      title: 'Reddit 2.0',
      keySkills: [
        'NextJS',
        'TailwindCSS',
        'Supabase',
        'GraphQL',
        'Stepzen',
        'Cloudinary',
        'Serverless APIs',
        'Reddit Auth',
        'Google Auth',
      ],
      image: 'project/reddit.png',
      desc: 'A Reddit clone with feed, add post, Google signin, Reddit Signin, voting, comment functionality designed and developed with NextJs, TailwindCSS, NextAuth, SQL database with GraphQL and much more... powered with PWA.',
      url: 'https://reddit-rebuild.vercel.app/',
    },
    {
      title: 'Rekindle',
      keySkills: [
        'React Native',
        'TailwindCSS',
        'Redux',
        'NodeJS',
        'MongoDB',
        'Express JS',
        'AWS',
        'Firebase',
        'Cashfree',
        'Push Notifications',
      ],
      image: 'project/rekindle.png',
      desc: 'Rekindle is a dating app to empower divorced, widowed & separated people by offering them exclusivity without a doubt. We are trying to build a community of verified profiles to weed out irrelevancy & save your time in finding your love!',
      url: 'https://linktr.ee/rekindleclub',
    },
    {
      title: 'CryptoPunk',
      keySkills: [
        'NextJS',
        'TailwindCSS',
        'Redux Toolkit',
        'Ant Design',
        'MongoDB',
        'Moralis',
        'Cloudinary',
        'Blockchain',
        'Web3',
        'Crypto APIs',
        'Serverless APIs',
        'Metamask',
        'Alchemy',
        'React Charts',
      ],
      image: 'project/cryptopunk.png',
      desc: 'An application based on deep learning and crypto powered by blockchain technology. This application consists of crypto market analysis, crypto prediction, NFTs listing and owning, sending and receiving crypto- blockchain smart contracts, and a blockchain authenticated user crypto profile.',
      url: 'https://cryptopunk-beta.vercel.app/',
    },
    {
      title: 'The Neuron Club',
      keySkills: [
        'NextJS',
        'TailwindCSS',
        'Redux',
        'Material-Tailwind',
        'MongoDB',
        'sanity.io CMS',
        'NextAuth',
        'Cloudinary',
        'Quill.js',
        'Framer Motion',
        'jwt auth',
        'Serverless APIs',
        'Coinbase Crypto payment',
      ],
      image: 'project/neuron.png',
      desc: "The Neuron Club (TNC) is an online gaming platform that allows users to predict global events across categories and win rewards. It's a full stack web application designed and developed with NextJs, TailwindCSS, Redux, MongoDB  with an inbuilt next server and much more ...",
      url: 'https://theneuron.club/',
    },
    {
      title: 'Instagram 2.0',
      keySkills: [
        'NextJS',
        'TailwindCSS',
        'Recoil',
        'Material-Tailwind',
        'Draft.js',
        'Firestore',
        'Firebase',
        'NextAuth',
        'Refresh token',
      ],
      image: 'project/instagram.png',
      desc: 'An Instagram clone with feed, add post, Google signin, like, comment functionality designed and developed with NextJs, TailwindCSS, Recoil, NextAuth and much more... powered with PWA.',
      url: 'https://instagram-rebuild.vercel.app/',
    },
    {
      title: 'Google Docs Rebuild',
      keySkills: [
        'NextJS',
        'TailwindCSS',
        'Material-Tailwind',
        'Draft.js',
        'Firestore',
        'Firebase',
      ],
      image: 'project/google-docs.png',
      desc: 'A Fully working Google Docs Clone that works with Google Authentication and Rich Text Editor. This application is build with NextJs, NextAuth, TailwindCSS, FireStore, Material Ui and Draft.js. Powered with PWA.',
      url: 'https://google-docs-rebuild.vercel.app/',
    },
    {
      title: 'Airbnb Rebuild',
      keySkills: [
        'NextJS',
        'TailwindCSS',
        'React Calendar',
        'Mapbox',
        'Geo Location',
      ],
      image: 'project/airbnb.png',
      desc: 'Airbnb Re-Design that includes landing page and Search Results. It includes Calender , Place & Hotel Search and Map functionality. It is designed with NextJs, TailwindCSS and Mapbox. ',
      url: 'https://airbnb-rebuild.vercel.app/',
    },
    {
      title: 'ShareBook Web App',
      keySkills: [
        'ReactJS',
        'Redux',
        'NodeJS',
        'ExpressJs',
        'MongoDB',
        'Socket.io',
        'TailwindCSS',
        'Framer-Motion',
      ],
      image: 'project/sharebook.png',
      desc: 'ShareBook is an intiative or a Book Sharing platform where user can get and share the book they want without any cost. It includes chat support system to contact book owner and many other functionalities.',
      url: 'https://sharebook.onrender.com/',
    },
    {
      title: 'Amazon 2.0',
      keySkills: [
        'NextJS',
        'Redux Thunk',
        'NextAuth',
        'TailwindCSS',
        'Stripe',
        'Web API',
        'Firebase',
        'Web hooks',
      ],
      image: 'project/amazon.png',
      desc: 'Amazon design with NextJs, complete E-Commerce functionality including Payment Processing (Stripe API) and User Authentication (Firebase). Powered with PWA',
      url: 'https://amazon-clone2.vercel.app/',
    },
    //             {
    //                 "title": "React in One",
    //                 "keySkills": ["ReactJS", "Material UI", "Weather API", "Pokemon API"],
    //                 "image": "project/react.png",
    //                 "desc": "A combined project of pure reactjs without using any addition modules. It includes the projects and techniques I've learnt during learning the ReactJS",
    //                 "url": "https://reactjs-demos-by-ak.web.app/"
    //             },
    //             {
    //                 "title": "Meditation Web App",
    //                 "keySkills": ["ReactJS", "Bootstrap", "Firebase"],
    //                 "image": "project/medi.png",
    //                 "desc": "A meditation control app that schedule and organize the meditation time period included with nature music and time duration.",
    //                 "url": "https://meditation-app-by-team-shark.web.app/"
    //             },
    {
      title: 'Covid Tracker',
      keySkills: ['ReactJS', 'Maps', 'Web API', 'Charts', ''],
      image: 'project/covid.png',
      desc: 'A covid tracker application that fetch the covid data from all over the world at allows you to get the details of the country you want.',
      url: 'https://covid-tracker-by-ak.web.app/',
    },
    {
      title: 'Spotify Rebuild',
      keySkills: ['ReactJS', 'Spotify API', 'Firebase', 'Spotify Auth'],
      image: 'project/spotify.png',
      desc: 'A Spotify web app that includes the functionality of original Spotify App i.e. the fetching of user playlists, user data, their songs etc. It provides a great user experience.',
      url: 'https://spotify-rebuild-2.vercel.app/',
    },
    {
      title: 'Netflix-Clone',
      keySkills: ['ReactJS', 'IMDB API', 'Firebase'],
      image: 'project/netflix.png',
      desc: 'A Netflix landing page. It includes IMDB Api for the movie data and allows the user to view the trailer and details of selected movie.',
      url: 'https://netflix-rebuild.vercel.app/',
    },
    //             {
    //                 "title": "Zoom-Clone",
    //                 "keySkills": ["Handlebars","NodeJS","ExpressJs","Socket.io","Peer JS"],
    //                 "image": "project/zoom.png",
    //                 "desc": "A Zoom clone that has live video and audio sharing functionality. It also have a chat system like original one and meeting joining, leaving functionality.",
    //                 "url": "https://zoom-clone-by-ak.herokuapp.com/"
    //             },
    {
      title: 'Super Chat',
      keySkills: ['ReactJS', 'Firebase', 'Google Auth'],
      image: 'project/superchat.png',
      desc: 'An authenticated group chat room. It includes google authentication, react tools for a great user experience',
      url: 'https://super-chat-48a7b.web.app/',
    },
  ],
}

export default data
